# -*- coding: utf-8 -*-
"""Data Cleaning & Reporting Automation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbU3dlb6926_mTXYWpl2G5poRkTbgIvB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
import plotly.express as px
from ydata_profiling import ProfileReport
from datetime import datetime
df = pd.read_csv("netflix_titles.csv")
# Basic Information
print("\nDataset Shape:")
print(df.shape)
print("\nColumn Information:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
# Create Backup Copy
raw_df = df.copy()
# Remove Duplicates
df.drop_duplicates(inplace=True)
# Handle Missing Values
df["director"] = df["director"].fillna("Unknown Director")
df["cast"] = df["cast"].fillna("Not Available")
df["country"] = df["country"].fillna(df["country"].mode()[0])
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])
df["duration"] = df["duration"].fillna("Unknown")
df["date_added"] = df["date_added"].fillna("January 1, 2020")
# Convert Date Column
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
# Remove Extra Spaces
text_columns = ["title", "director", "cast", "country", "listed_in", "description"]
for col in text_columns:
    df[col] = df[col].astype(str).str.strip()
# Standardize Text Format
df["type"] = df["type"].str.upper()
df["country"] = df["country"].str.title()
# Feature Engineering
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month_name()
# Separate Movie Duration
df["duration_number"] = df["duration"].str.extract(r"(\d+)")
df["duration_number"] = pd.to_numeric(df["duration_number"],errors="coerce")
# Save Cleaned Dataset
df.to_csv("cleaned_netflix_titles.csv", index=False)
print("\nCleaned Dataset Saved Successfully")
# Missing Value Visualization
plt.figure(figsize=(12, 6))
msno.matrix(df)
plt.title("Missing Values Matrix")
plt.savefig("missing_values_matrix.png")
plt.close()
# Content Type Distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x="type")
plt.title("Content Type Distribution")
plt.xticks(rotation=0)
plt.savefig("content_type_distribution.png")
plt.close()
# Top 10 Countries
top_countries = df["country"].value_counts().head(10)
plt.figure(figsize=(12, 6))
top_countries.plot(kind="bar")
plt.title("Top 10 Countries")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.savefig("top_countries.png")
plt.close()
# Release Year Trend
release_trend = df["release_year"].value_counts().sort_index()
plt.figure(figsize=(14, 6))
release_trend.plot()
plt.title("Netflix Release Trend")
plt.xlabel("Release Year")
plt.ylabel("Count")
plt.savefig("release_trend.png")
plt.close()
# Ratings Distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=df,y="rating",order=df["rating"].value_counts().index)
plt.title("Ratings Distribution")
plt.savefig("ratings_distribution.png")
plt.close()
# Interactive Plotly Chart
fig = px.histogram( df, x="release_year", color="type", title="Netflix Content Release Year Distribution")
fig.write_html("interactive_release_dashboard.html")
# Automated Summary Report
summary_report = {
    "Total Rows": [df.shape[0]],
    "Total Columns": [df.shape[1]],
    "Total Missing Values": [df.isnull().sum().sum()],
    "Duplicate Rows Removed": [raw_df.duplicated().sum()],
    "Total Movies": [df[df["type"] == "MOVIE"].shape[0]],
    "Total TV Shows": [df[df["type"] == "TV SHOW"].shape[0]],
    "Unique Countries": [df["country"].nunique()],
    "Most Common Rating": [df["rating"].mode()[0]],
    "Report Generated On": [datetime.now()]
}
summary_df = pd.DataFrame(summary_report)
# Save Excel Report
with pd.ExcelWriter("Netflix_Automated_Report.xlsx",engine="xlsxwriter") as writer:
    df.to_excel(writer,sheet_name="Cleaned_Data",index=False)
    summary_df.to_excel(writer,sheet_name="Summary_Report",index=False)
print("\nExcel Report Generated Successfully")
# Generate Advanced HTML Profiling Report
profile = ProfileReport(df,title="Netflix Data Profiling Report",explorative=True)
profile.to_file("Netflix_Profiling_Report.html")
print("\nAdvanced HTML Profiling Report Generated")
# Final Console Summary
print("\nData Cleaning & Reporting Automation Completed Successfully")
print("\nGenerated Files:")
print("1. cleaned_netflix_titles.csv")
print("2. Netflix_Automated_Report.xlsx")
print("3. Netflix_Profiling_Report.html")
print("4. missing_values_matrix.png")
print("5. content_type_distribution.png")
print("6. top_countries.png")
print("7. release_trend.png")
print("8. ratings_distribution.png")
print("9. interactive_release_dashboard.html")

pip install pandas numpy openpyxl matplotlib plotly seaborn sweetviz ydata-profiling missingno xlsxwriter